import json
import os
import base64
from datetime import datetime, timedelta
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    RunReportRequest, DateRange, Metric, Dimension
)
from google.oauth2 import service_account
import anthropic
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ── Configuration (reads from GitHub Secrets) ─────────────────
PROPERTY_ID    = "543326297"
EMAIL_TO       = "caryn.campelo@gmail.com"
EMAIL_FROM     = "caryn.campelo@gmail.com"
EMAIL_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]
# ─────────────────────────────────────────────────────────────

def get_ga4_credentials():
    key_b64 = os.environ["GA4_KEY_JSON"]
    key_json = base64.b64decode(key_b64).decode("utf-8")
    key_dict = json.loads(key_json)
    return service_account.Credentials.from_service_account_info(
        key_dict,
        scopes=["https://www.googleapis.com/auth/analytics.readonly"]
    )

def fetch_ga4_data():
    credentials = get_ga4_credentials()
    client = BetaAnalyticsDataClient(credentials=credentials)

    today = datetime.today()
    yesterday = today - timedelta(days=1)
    date_range = DateRange(
        start_date=yesterday.strftime("%Y-%m-%d"),
        end_date=yesterday.strftime("%Y-%m-%d")
    )

    overview = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        metrics=[
            Metric(name="sessions"),
            Metric(name="activeUsers"),
            Metric(name="bounceRate"),
            Metric(name="averageSessionDuration"),
        ]
    ))

    row = overview.rows[0].metric_values
    sessions  = int(row[0].value)
    users     = int(row[1].value)
    bounce    = round(float(row[2].value) * 100, 1)
    avg_dur_s = int(float(row[3].value))
    avg_dur   = f"{avg_dur_s // 60}m {avg_dur_s % 60}s"

    pages_report = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        dimensions=[Dimension(name="pagePath")],
        metrics=[Metric(name="sessions")],
        limit=5
    ))

    top_pages = [
        {"page": r.dimension_values[0].value, "sessions": int(r.metric_values[0].value)}
        for r in pages_report.rows
    ]

    sources_report = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        dimensions=[Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions")],
        limit=5
    ))

    traffic_sources = [
        {"source": r.dimension_values[0].value, "sessions": int(r.metric_values[0].value)}
        for r in sources_report.rows
    ]

    return {
        "date": yesterday.strftime("%A, %B %d %Y"),
        "sessions": sessions,
        "users": users,
        "bounce_rate": bounce,
        "avg_session": avg_dur,
        "top_pages": top_pages,
        "traffic_sources": traffic_sources
    }


def generate_summary(data):
    client = anthropic.Anthropic()

    prompt = f"""
You are a friendly analytics assistant. Write a concise, plain-English daily 
website analytics summary for a non-technical website owner.

Here is yesterday's data ({data['date']}):
- Sessions: {data['sessions']}
- Unique visitors: {data['users']}
- Bounce rate: {data['bounce_rate']}%
- Average session duration: {data['avg_session']}
- Top pages: {json.dumps(data['top_pages'], indent=2)}
- Traffic sources: {json.dumps(data['traffic_sources'], indent=2)}

Write 3 short paragraphs:
1. A headline summary of how yesterday went overall
2. What content performed best and where traffic came from
3. One small actionable suggestion for today

Keep it warm, concise, and encouraging. No bullet points — just friendly paragraphs.
"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


def send_email(subject, body):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_FROM
    msg["To"]      = EMAIL_TO

    html = f"""
    <html><body style="font-family: sans-serif; max-width: 600px; margin: auto; color: #333;">
      <h2 style="color: #185FA5;">Daily site report</h2>
      <p style="color: #888; font-size: 13px;">Auto-generated by your analytics agent</p>
      <hr style="border: none; border-top: 1px solid #eee;">
      {"".join(f"<p>{para}</p>" for para in body.split(chr(10)) if para.strip())}
    </body></html>
    """

    msg.attach(MIMEText(body, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL_FROM, EMAIL_PASSWORD)
        server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())

    print(f"Email sent to {EMAIL_TO}")


if __name__ == "__main__":
    print("Fetching GA4 data...")
    data = fetch_ga4_data()

    print("Generating AI summary...")
    summary = generate_summary(data)

    date = data['date']
    subject = f"Your site analytics: {date}"
    send_email(subject, summary)
    print("Done!")
