import json
import os
from datetime import datetime, timedelta
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    RunReportRequest, DateRange, Metric, Dimension
)
from google.oauth2 import service_account
import anthropic
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ── Configuration ─────────────────────────────────────────────
KEY_FILE   = "/Users/caryncampelo/Desktop/google cloud/my-analytics-agent-500914-c384bf6480cc.json"
PROPERTY_ID = "543326297"
EMAIL_TO    = "caryn.campelo@gmail.com"

# Gmail: use an App Password (not your regular password)
# Generate one at: myaccount.google.com/apppasswords
EMAIL_FROM     = "caryn.campelo@gmail.com"
EMAIL_PASSWORD = "sqkbfsnyodksirku"   # <-- fill this in
# ─────────────────────────────────────────────────────────────


def fetch_ga4_data():
    credentials = service_account.Credentials.from_service_account_file(
        KEY_FILE,
        scopes=["https://www.googleapis.com/auth/analytics.readonly"]
    )
    client = BetaAnalyticsDataClient(credentials=credentials)

    today = datetime.today()
    last_monday = today - timedelta(days=today.weekday() + 7)
    last_sunday = last_monday + timedelta(days=6)
    date_range = DateRange(
        start_date=last_monday.strftime("%Y-%m-%d"),
        end_date=last_sunday.strftime("%Y-%m-%d")
    )

    # --- Overall metrics ---
    overview = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        metrics=[
            Metric(name="sessions"),
            Metric(name="activeUsers"),
            Metric(name="bounceRate"),
            Metric(name="averageSessionDuration"),
        ]
    ))

    row = overview.rows[0].metric_values
    sessions   = int(row[0].value)
    users      = int(row[1].value)
    bounce     = round(float(row[2].value) * 100, 1)
    avg_dur_s  = int(float(row[3].value))
    avg_dur    = f"{avg_dur_s // 60}m {avg_dur_s % 60}s"

    # --- Top pages ---
    pages_report = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        dimensions=[Dimension(name="pagePath")],
        metrics=[Metric(name="sessions")],
        limit=5
    ))

    top_pages = [
        {
            "page": r.dimension_values[0].value,
            "sessions": int(r.metric_values[0].value)
        }
        for r in pages_report.rows
    ]

    # --- Traffic sources ---
    sources_report = client.run_report(RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[date_range],
        dimensions=[Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions")],
        limit=5
    ))

    traffic_sources = [
        {
            "source": r.dimension_values[0].value,
            "sessions": int(r.metric_values[0].value)
        }
        for r in sources_report.rows
    ]

    return {
        "week": f"{last_monday.strftime('%b %d')} – {last_sunday.strftime('%b %d, %Y')}",
        "sessions": sessions,
        "users": users,
        "bounce_rate": bounce,
        "avg_session": avg_dur,
        "top_pages": top_pages,
        "traffic_sources": traffic_sources
    }


def generate_summary(data):
    client = anthropic.Anthropic()   # reads ANTHROPIC_API_KEY from environment

    prompt = f"""
You are a friendly analytics assistant. Write a concise, plain-English weekly 
website analytics summary for a non-technical website owner. 

Here is last week's data ({data['week']}):
- Sessions: {data['sessions']}
- Unique visitors: {data['users']}
- Bounce rate: {data['bounce_rate']}%
- Average session duration: {data['avg_session']}
- Top pages: {json.dumps(data['top_pages'], indent=2)}
- Traffic sources: {json.dumps(data['traffic_sources'], indent=2)}

Write 3–4 short paragraphs:
1. A headline summary of how the week went overall
2. What content performed best and why it might have
3. Where traffic came from and what that means
4. One concrete suggestion for next week

Keep it warm and actionable. No bullet points — just friendly paragraphs.
"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


def send_email(subject, body):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_FROM
    msg["To"]      = EMAIL_TO

    html = f"""
    <html><body style="font-family: sans-serif; max-width: 600px; margin: auto; color: #333;">
      <h2 style="color: #185FA5;">📊 Weekly site report</h2>
      <p style="color: #888; font-size: 13px;">Auto-generated by your analytics agent</p>
      <hr style="border: none; border-top: 1px solid #eee;">
      {"".join(f"<p>{para}</p>" for para in body.split(chr(10)) if para.strip())}
    </body></html>
    """

    msg.attach(MIMEText(body, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL_FROM, EMAIL_PASSWORD)
        server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())

    print(f"Email sent to {EMAIL_TO}")


if __name__ == "__main__":
    print("Fetching GA4 data...")
    data = fetch_ga4_data()

    print("Generating AI summary...")
    summary = generate_summary(data)

    week = data['week']
    subject = f"Your site analytics: {week}"
    send_email(subject, summary)
    print("Done!")
